version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: quran-backend:latest
    container_name: quran-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./app.db
      - CORS_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
      # Set at runtime in prod: JWT_SECRET=your-strong-secret
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    image: quran-frontend:latest
    container_name: quran-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    restart: unless-stopped
