version: "3.9"

services:
  traefik:
    image: traefik:v3.1
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --entrypoints.web.address=:80
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

  web:
    build: .
    env_file:
      - .env
    command: ["/bin/sh","-c","python manage.py migrate && gunicorn config.wsgi:application -b 0.0.0.0:8000 --workers 2"]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`${APP_HOST:-localhost}`) || HostRegexp(`{catchall:.+}`)"
      - "traefik.http.routers.web.entrypoints=web"
    volumes:
      - .:/app
    restart: unless-stopped
    depends_on:
      - traefik
