services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: quran-backend:latest
    container_name: quran-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./app.db
      - CORS_ORIGINS=http://localhost:3000
      - JWT_SECRET=dev-secret-change-me
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: quran-frontend:latest
    container_name: quran-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE=http://localhost:8000
    depends_on:
      - backend
    restart: unless-stopped
