services:
  web:
    build: .
    env_file:
      - .env
    environment:
      # Ensure app listens on 8000 and runs in dev-friendly mode unless overridden
      PORT: "8000"
      DEBUG: "true"
      ALLOWED_HOSTS: "*"
    ports:
      - "8000:8000"  # host:container
    volumes:
      - .:/app
    restart: unless-stopped
