name: CI • Build • Release • DockerHub

on:
  push:
    branches: [ "nextjs" ]
    tags: [ "v*.*.*" ]
  pull_request:
    branches: [ "nextjs" ]

env:
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/quran-audio-frontend

jobs:
  build:
    name: Build (Next.js)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install deps
        run: |
          if [ -f package-lock.json ]; then
            npm ci --legacy-peer-deps
          else
            npm install --legacy-peer-deps
          fi

      - name: Ensure ESLint config (non-interactive)
        run: |
          if [ ! -f .eslintrc.json ] && [ ! -f .eslintrc.js ]; then
            echo '{ "extends": ["next/core-web-vitals"] }' > .eslintrc.json
          fi

      - name: Lint
        run: npm run lint --if-present

      - name: Build
        run: npm run build

      - name: Notify Telegram (build status)
        if: always()
        run: |
          if [ -n "${{ secrets.TELEGRAM_BOT_TOKEN }}" ] && [ -n "${{ secrets.TELEGRAM_CHAT_ID }}" ]; then
            STATUS="✅ Build passed"
            if [ "${{ job.status }}" != "success" ]; then STATUS="❌ Build failed"; fi
            MSG="*${{ github.repository }}*\nJob: *Build*\nBranch/Ref: \`${{ github.ref }}\`\nCommit: \`${{ github.sha }}\`\nStatus: ${STATUS}"
            curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage"               -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}"               -d parse_mode="Markdown"               --data-urlencode "text=${MSG}" >/dev/null || true
          fi

  docker:
    name: Docker Build & Push
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      - name: Build and push
        id: buildpush
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Notify Telegram (docker status)
        if: always()
        env:
          TAGS: ${{ steps.meta.outputs.tags }}
        run: |
          if [ -n "${{ secrets.TELEGRAM_BOT_TOKEN }}" ] && [ -n "${{ secrets.TELEGRAM_CHAT_ID }}" ]; then
            STATUS="✅ Docker push succeeded"
            if [ "${{ job.status }}" != "success" ]; then STATUS="❌ Docker push failed"; fi
            MSG="*${{ github.repository }}*\nJob: *Docker*\nImage: \`${{ env.IMAGE_NAME }}\`\nTags:\n\`${TAGS}\`\nBranch/Ref: \`${{ github.ref }}\`\nCommit: \`${{ github.sha }}\`\nStatus: ${STATUS}"
            curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage"               -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}"               -d parse_mode="Markdown"               --data-urlencode "text=${MSG}" >/dev/null || true
          fi

  release:
    name: GitHub Release (on tag)
    runs-on: ubuntu-latest
    needs: [ build, docker ]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
      - uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true

      - name: Notify Telegram (release status)
        if: always()
        run: |
          if [ -n "${{ secrets.TELEGRAM_BOT_TOKEN }}" ] && [ -n "${{ secrets.TELEGRAM_CHAT_ID }}" ]; then
            STATUS="✅ Release created"
            if [ "${{ job.status }}" != "success" ]; then STATUS="❌ Release failed"; fi
            MSG="*${{ github.repository }}*\nJob: *Release*\nTag: \`${{ github.ref_name }}\`\nStatus: ${STATUS}"
            curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage"               -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}"               -d parse_mode="Markdown"               --data-urlencode "text=${MSG}" >/dev/null || true
          fi
