name: CI • Build • Release • DockerHub

on:
  push:
    branches: ["nextjs"]
    tags: ["v*.*.*"]
  pull_request:
    branches: ["nextjs"]

env:
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/quran

jobs:
  build:
    name: Build (Next.js)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install deps
        run: |
          if [ -f package-lock.json ]; then
            npm ci --legacy-peer-deps
          else
            npm install --legacy-peer-deps
          fi

      - name: Ensure ESLint config (non-interactive)
        run: |
          if [ ! -f .eslintrc.json ] && [ ! -f .eslintrc.js ]; then
            echo '{ "extends": ["next/core-web-vitals"] }' > .eslintrc.json
          fi

      - name: Lint
        run: npm run lint --if-present

      - name: Build
        run: npm run build

  docker:
    name: Docker Build & Push
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  release:
    name: GitHub Release (on tag)
    runs-on: ubuntu-latest
    needs: [build, docker]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
      - uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
